### PR TITLE
Implements double-sized sprites

### PR DESCRIPTION
**Pull request by theflynn49**
-Implements double-sized sprites (control reg 01 bit 0)
-small change in fake serial GG register

### CODE REVIEW

**Comment by sorgelig** [comment]
Is it ready for release or you want to add more improvements before release?

**Comment by theflynn49** [comment]
I am working on the serial/parallel register emulation of the game gear, but it's small fish.
This is a good milestone as it's the last (known to me) feature of the VDP engine ... 
So I let you judge.

**Comment by sorgelig** [comment]
ok. then will wait for serial/parallel register emulation, then release

**Comment by theflynn49** [comment]
Ok. #36 is ready ;)

**Pull request merged**
